"""empty message

Revision ID: 39c3d264bff5
Revises: 
Create Date: 2025-04-06 13:52:12.133621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c3d264bff5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_client'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone')
    )
    op.create_table('mecanicien',
    sa.Column('id_mecanicien', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('specialite', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_mecanicien')
    )
    op.create_table('piece',
    sa.Column('id_piece', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_piece')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicule',
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.Column('immatriculation', sa.String(length=20), nullable=False),
    sa.Column('marque', sa.String(length=50), nullable=False),
    sa.Column('modele', sa.String(length=50), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['client.id_client'], ),
    sa.PrimaryKeyConstraint('id_vehicule'),
    sa.UniqueConstraint('immatriculation')
    )
    op.create_table('reparation',
    sa.Column('id_reparation', sa.Integer(), nullable=False),
    sa.Column('date_entree', sa.Date(), nullable=False),
    sa.Column('date_sortie_prevue', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_vehicule'], ['vehicule.id_vehicule'], ),
    sa.PrimaryKeyConstraint('id_reparation')
    )
    op.create_table('intervention',
    sa.Column('id_intervention', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cout', sa.Float(), nullable=False),
    sa.Column('duree', sa.Integer(), nullable=False),
    sa.Column('id_reparation', sa.Integer(), nullable=False),
    sa.Column('id_mecanicien', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_mecanicien'], ['mecanicien.id_mecanicien'], ),
    sa.ForeignKeyConstraint(['id_reparation'], ['reparation.id_reparation'], ),
    sa.PrimaryKeyConstraint('id_intervention')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intervention')
    op.drop_table('reparation')
    op.drop_table('vehicule')
    op.drop_table('user')
    op.drop_table('piece')
    op.drop_table('mecanicien')
    op.drop_table('client')
    # ### end Alembic commands ###
